57 create user management
GenZHAW/GNX_Webapp pull request #94
Opened 2023-05-15 16:14 UTC by BadrOutiti

2023-05-15 19:12 UTC, jondef commented
It's kind of a mess but it should run

2023-05-16 06:00 UTC, jaypi95 requested changes
Please remove the .env and fix the issue with updating the username. Great work otherwise, looks good.

2023-05-16 06:00 UTC, jaypi95 commented on .env
Genius move, committing the .env. This should be in .gitignore, what happened?

2023-05-16 06:00 UTC, jaypi95 commented on js/clientJS/usermanagement.js
There is a problem somewhere in here I think. When trying to change the username, the console throws this error and username does not get updated: 
![image](https://github.com/GenZHAW/GNX_Webapp/assets/32958970/ed537e06-afe1-4d21-8fbc-1031f9fc45a7)

2023-05-16 06:21 UTC, jondef commented on .env
> Genius move, committing the .env. This should be in .gitignore, what happened?

the commit should be gone when squashing I think so it should be okay

2023-05-16 06:22 UTC, jaypi95 commented on .env
The .env will still be in the repository including the password.

2023-05-16 06:22 UTC, jaypi95 commented on .env
Also the commit will be visible in the PR despite squashing

2023-05-16 06:24 UTC, jondef commented on .env
> Also the commit will be visible in the PR despite squashing

but if we delete the env file now with a new commit, is it still gonna be visible? Cuz when squashifying the commits it's gonna disappear no?

2023-05-17 14:32 UTC, BadrOutiti commented on js/clientJS/usermanagement.js
This bug is also seen in the dev branche so it has nothing to do with this merge request.

I will make a new issue for this.

2023-05-17 14:51 UTC, BadrOutiti commented on js/clientJS/usermanagement.js
Nevermind it was a bug, but i fixed it with the last commit.

2023-05-18 09:03 UTC, jaypi95-sc commented on .env
The history will only be squashed in the develop branched where it was merged into. When you look at the PRs, the commits are still in there.

2023-05-18 09:15 UTC, jaypi95 approved these changes
Nice fix with the usermanagement. I retested it and see that it works. I assume that the .env will get deleted from the computers of people who have it also committed for some reason. It doesn't matter since this .env has become obsolete now anyways. @SilvanBaach has changed all passwords already.

2023-05-18 09:16 UTC, merged